// <auto-generated />
using InfiniteIP.DbUtils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfiniteIP.Migrations
{
    [DbContext(typeof(InfiniteContext))]
    [Migration("20250417113659_addedsowhours")]
    partial class addedsowhours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfiniteIP.Models.GmSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("accountId")
                        .HasColumnType("integer");

                    b.Property<string>("billable")
                        .HasColumnType("text");

                    b.Property<string>("billrate")
                        .HasColumnType("text");

                    b.Property<string>("brspdMgr")
                        .HasColumnType("text");

                    b.Property<string>("duration")
                        .HasColumnType("text");

                    b.Property<string>("enddate")
                        .HasColumnType("text");

                    b.Property<decimal>("hours")
                        .HasColumnType("numeric");

                    b.Property<string>("loadedrate")
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("payrate")
                        .HasColumnType("text");

                    b.Property<string>("program")
                        .HasColumnType("text");

                    b.Property<int>("projectId")
                        .HasColumnType("integer");

                    b.Property<string>("roleaspersow")
                        .HasColumnType("text");

                    b.Property<int>("sow")
                        .HasColumnType("integer");

                    b.Property<string>("startdate")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GmSheet");
                });
#pragma warning restore 612, 618
        }
    }
}
